ALTER SESSION SET NLS_DATE_FORMAT  = 'DD-MON-YY HH24:MI:SS';

SELECT trunc((((86400*(sysdate-APPLIED_TIME))/60)/60)/24) "Days" 
FROM V$LOGSTDBY_PROGRESS;

SELECT trunc(((86400*(sysdate-APPLIED_TIME))/60)/60)-24*(trunc((((86400*(sysdate-APPLIED_TIME))/60)/60)/24)) "Hrs" 
FROM V$LOGSTDBY_PROGRESS;

select * from V$LOGSTDBY_STATS;

COLUMN STATUS FORMAT A60

SELECT EVENT_TIME, STATUS, EVENT 
FROM DBA_LOGSTDBY_EVENTS
ORDER BY EVENT_TIMESTAMP, COMMIT_SCN, CURRENT_SCN;

SELECT APPLIED_TIME, LATEST_TIME, MINING_TIME, RESTART_TIME
FROM V$LOGSTDBY_PROGRESS;

SELECT SESSION_ID, STATE FROM V$LOGSTDBY_STATE;

SELECT TYPE, STATUS_CODE, STATUS FROM V$LOGSTDBY_PROCESS;

ALTER DATABASE START LOGICAL STANDBY APPLY;


